name: JenMurphyDesign
favicon: null
layout_spectrum: 0.57409278745763
typography_spectrum: 0.31259178929030895
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.14551617461256683
  lightness: 0.9514272809028625
  saturation: 0.2654240212868899
  rhythmicContrast: 0.12736683897674084
purpose: []
